### ISSUE TITLE
TCP messages are not sent

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/mariadb-to-graylog#4]
Before switching to Python 3, netcat showed TCP messages. Now even if you send 1K messages it remains blank.

**Comment by federico-razzoli** [comment]
If we don't handle the error:
```
Traceback (most recent call last):
  File "/Users/federico/repos/mariadb-to-graylog/./mariadb-log-consumer.py", line 746, in <module>
    Registry.consumer.start()
  File "/Users/federico/repos/mariadb-to-graylog/./mariadb-log-consumer.py", line 368, in start
    self._consuming_loop()
  File "/Users/federico/repos/mariadb-to-graylog/./mariadb-log-consumer.py", line 526, in _consuming_loop
    self._error_log_consuming_loop()
  File "/Users/federico/repos/mariadb-to-graylog/./mariadb-log-consumer.py", line 688, in _error_log_consuming_loop
    self._error_log_process_line(source_line)
  File "/Users/federico/repos/mariadb-to-graylog/./mariadb-log-consumer.py", line 618, in _error_log_process_line
    self._process_message()
  File "/Users/federico/repos/mariadb-to-graylog/./mariadb-log-consumer.py", line 498, in _process_message
    self._GRAYLOG['client_tcp'].send(
  File "/Users/federico/repos/mariadb-to-graylog/lib_consumer/graylog_client_udp.py", line 30, in send
    self.socket.socket(self.socket.AF_INET, self.socket.SOCK_DGRAM).sendto(
TypeError: a bytes-like object is required, not 'str'
```

**Comment by federico-razzoli** [comment]
Solution: we convert the string to `bytearray` assuming that it's encoded as `us-ascii`. This seems to be true for both the error log and the slow log.

```
federico@Federicos-MacBook-Air mariadb-to-graylog % file --raw --mime logs/error.log
logs/error.log: text/plain; charset=us-ascii
federico@Federicos-MacBook-Air mariadb-to-graylog % file --raw --mime logs/slow.log 
logs/slow.log: text/plain; charset=us-ascii
```

**Comment by federico-razzoli** [comment]
Fixed.
